SUBROUTINE GET_MANUFACTURER(KTYPE,MANUFACTURER)
    USE PARKIND1, ONLY : JPRB,JPIM

    IMPLICIT NONE
    INTEGER(KIND=JPIM),INTENT(IN) :: KTYPE
    CHARACTER(len=42),INTENT(OUT) :: MANUFACTURER
    INTEGER(KIND=JPIM) :: MAN_CODE

    MAN_CODE = MODULO(KTYPE, 100)

    IF ( MAN_CODE == 00 ) MANUFACTURER = "Senvion-Repower/Jacobs/HSW Husum/Kenersys"
    IF ( MAN_CODE == 01 ) MANUFACTURER = "VESTAS ONSHORE"
    IF ( MAN_CODE == 02 ) MANUFACTURER = "NORDEX"
    IF ( MAN_CODE == 03 ) MANUFACTURER = "GE/Enron"
    IF ( MAN_CODE == 04 ) MANUFACTURER = "Fuhrlaender/Protec MD"
    IF ( MAN_CODE == 05 ) MANUFACTURER = "NEG MICON/Nordtank"
    IF ( MAN_CODE == 06 ) MANUFACTURER = "Siemens SWT/GAMESA/BONUS ONSHORE"
    IF ( MAN_CODE == 07 ) MANUFACTURER = "DeWIND"
    IF ( MAN_CODE == 08 ) MANUFACTURER = "Enercon"
    IF ( MAN_CODE == 09 ) MANUFACTURER = "VENSYS"
    IF ( MAN_CODE == 20 ) MANUFACTURER = "Tacke"
    IF ( MAN_CODE == 21 ) MANUFACTURER = "KNMI onshore reference turbine"
    IF ( MAN_CODE == 22 ) MANUFACTURER = "Goldwind (China)"
    IF ( MAN_CODE == 23 ) MANUFACTURER = "Leitwind (Italy)"
    IF ( MAN_CODE == 24 ) MANUFACTURER = "ACCIONA (Spain)"
    IF ( MAN_CODE == 25 ) MANUFACTURER = "KONCAR Croatian manufacturer"
    IF ( MAN_CODE == 26 ) MANUFACTURER = "Frisia"
    IF ( MAN_CODE == 27 ) MANUFACTURER = "Schuetz"
    IF ( MAN_CODE == 28 ) MANUFACTURER = "Envision (China Shanghai)"
    IF ( MAN_CODE == 29 ) MANUFACTURER = "Eno Energy"
    IF ( MAN_CODE == 40 ) MANUFACTURER = "DDIS France"
    IF ( MAN_CODE == 41 ) MANUFACTURER = "FWT"
    IF ( MAN_CODE == 42 ) MANUFACTURER = "Wind world (DK)"
    IF ( MAN_CODE == 43 ) MANUFACTURER = "Kleinwind SW10"
    IF ( MAN_CODE == 44 ) MANUFACTURER = "Seewind"
    IF ( MAN_CODE == 10 ) MANUFACTURER = "Senvion OFFSHORE"
    IF ( MAN_CODE == 11 ) MANUFACTURER = "Vestas OFFSHORE"
    IF ( MAN_CODE == 16 ) MANUFACTURER = "SWT OFFSHORE"
    IF ( MAN_CODE == 30 ) MANUFACTURER = "Haliade OFFSHORE"
    IF ( MAN_CODE == 31 ) MANUFACTURER = "REF OFFSHORE (KNMI)"
    IF ( MAN_CODE == 32 ) MANUFACTURER = "Adwen"
    IF ( MAN_CODE == 33 ) MANUFACTURER = "Areva"
    IF ( MAN_CODE == 34 ) MANUFACTURER = "BARD"
END SUBROUTINE