name: Setup GitHub Credentials
description: Sets up git config to use token for GitHub URLs

inputs:
  github_token:
    description: GitHub token to use
    required: true

runs:
  using: composite
  steps:
    - name: Set github credentials
      run: |
        sed -i 's#git@github.com#https://github.com#g' pyproject.toml
        git config --global url."https://${{ inputs.github_token }}@github.com/".insteadOf "https://github.com/"
      shell: bash
